### ISSUE TITLE
Tracking: Add OpenGliderNetwork integration

### ISSUE THREAD

**Issue by kerel-fs** [skylines-project/skylines#419]
We could use data from the [OpenGliderNetwork](http://glidernet.org) to extend the tracking coverage of skylines.

To enable this feature, a user would enter their FLARM-ID (or ICAO-address, henceforth referred as `ogn_address`) into skylines.
An external daemon (_ogn-skylines-gateway_) would forward corresponding fix-packets to skylines.
## Architecture
- _skylines_
  - [ ] saves mapping `ogn_address` <--> `skylines_tracking_key`
  - [ ] serves this mapping for an authenticated service (_ogn-skylines-gateway_)
- [_ogn-skylines-gateway_](https://github.com/kerel-fs/ogn-skylines-gateway)
  - [ ] fetches the mapping from _skylines_
  - [x] forwards fixes from _glidernet_ to _skylines_, using the `skylines_tracking_key`
## Remarks
- The relation `ogn_address`(usually a flarm device) <--> `skylines_user` could be highly volatile (e.g. in glider clubs). **solution:** Enable optional time-limited relations by adding the timestamps `ownership_from` and `ownership_until` to the mapping
- The _ogn-skylines-gateway_ should be trusted, as it handles foreign `tracking_keys`.
- Should the time-delay feature be implemented (at the moment not supported by _ogn-skylines-gateway_)?

Help/Tips in the skylines-/user-interface-related tasks would be highly appreciated.
What are your thoughts about it?

**Comment by kerel-fs** [comment]
yesterday, @lordfolken suggested the following:
If the gps source of xcsoar (or any other 'normal' client) differs from flarm (or any other ogn-device),
it could be necessary to merge the data to prevent artifacts (position hopping).
Alternatively select only one feed (e.g. based on packet rate).

**Comment by Turbo87** [comment]
@kerel-fs we actually had OGN implemented at some point in the past but removed it again after some of the developers were uncomfortable with the privacy issues of the system. I'm personally open to the system, but since the legality of the system under the German law is still questionable we need to be very careful here.

**Comment by lordfolken** [comment]
In this implementation the user has to enter an association between his flarmid and his skylines id. I think this should be sufficient for an agreement, to use OGN's data for that particular user?

**Comment by kerel-fs** [comment]
@Turbo87
Yes, in my opinion, users must **opt-in** to enable tracking rather than **opt-out*** to disable it.
To establish this in OGN, pilots can opt-in their devices in the [DeviceDataBase (DDB)](https://ddb.glidernet.org)**
and only packets of registered devices are forwarded by the OGN-receivers.
This receiver-feature can be enabled with [kerel-fs/ogn-privacy-filter](https://github.com/kerel-fs/ogn-privacy-filter) and
since version 0.2.4 with the native OGN receiver software***.

Thus, I think the legality of the system regarding privacy isn't questionable anymore.

Nevertheless we should respect "no-track"-entries from the DDB,
since not all receiver-operators activated the feature above (@lordfolken).

-

\*: opt-out like the "No-Track"-flag in FLARM-settings (respected by OGN of course)
\*\*: historically not FlarmNet, see [FlarmNet FAQ](http://www.flarmnet.org/index.php/en/faqs-and-answers)
\*\*\*:optional, as requested by receiver operators from other countries

**Comment by Turbo87** [comment]
good, sounds like you are aware of the situation then. unfortunately I'm going on vacation next monday for a few weeks and won't be able to provide any assistance on this issue. hopefully @TobiasLohner will be available for that though. otherwise post your questions, issues and PRs here and I'll try to answer once I get back in January.

**Comment by kerel-fs** [comment]
Hi, a short status update on this issue:
[ogn-skylines-gateway](https://github.com/kerel-fs/ogn-skylines-gateway) is now able to forward packets from ogn to skylines for configured users.
Users can be added/deleted via command-line and via an experimental [HTTP-API](https://github.com/kerel-fs/ogn-skylines-gateway/tree/feature/api#api).
To allow users to add their devices, my idea was to add an [ogn-related section](http://paste.debian.net/hidden/da716ee5/) to `/settings/tracking` in skylines which talks to the HTTP-API  in the background.

It would be nice if this gateway runs on the same network/host like skylines to avoid superfluous hops for forwarded packets. Is it feasible to deploy a (docker?) container at skylines which locally exposes the HTTP-API to skylines?

Any thoughts about the general approach, should it be done completely different?

**Comment by kerel-fs** [comment]
After several discussions in the IRC channel, I would like to state and solve the mentioned issues regarding the acceptance of OGN by glider pilots in general and skylines in particular.
### Issues (and possible solutions)
1. someone could signup using a foreign flarmid
  - affected FLARM must set config flag NoTrack=False (unfortunately the default)
  - flarmid must be registered in the DDB (requires a valid e-mail address, but not real authentication)
  - DDB flags for flarmid must be "tracked"=True, "identified"=True
  - --> causes fraudulent attribution, but no privacy violation

2. anybody can simply ignore the "NoTrack" flag
  - trust in OGN receiver operators is needed
  - OGN receiver operators must respect the DDB and "NoTrack" flag
  - **solution**
    - monitor OGN traffic (out of scope for skylines, but POC at https://ogn.peanutpod.de/receivers-privacy.json)
    - we could accept trusted stations only

3. list of contact persons for OGN receivers (responsibility of OGN receiver operators)
  - **solution**
    - http://wiki.glidernet.org/list-of-receivers
    - https://ogn.peanutpod.de/

4. OGN was misusing FLARM
  - **"solution"**
    - FLARM introduced the "NoTrack" flag
    - FLARM and some OGN devs communicate actively
    - FLARM operates an OGN receiver themself (https://ogn.peanutpod.de/#/receivers/Rigi)

Can someone of the skylines maintainers comment on this or even give a go/no-go (@Turbo87)?

**Comment by Turbo87** [comment]
@kerel-fs sorry for being so unresponsive. SkyLines didn't have high priority for me in the last year but now that it's spring it sparked my interest again.

> Can someone of the skylines maintainers comment on this or even give a go/no-go (@Turbo87)?

:+1: but keep me in the loop on what and how you want to implement it.

**Comment by kerel-fs** [comment]
Currently I'm stuck adding the UI in skylines (user input for the ogn_address/flarmid). The forwarding of fixes of a given ogn_address to skylines works already (code currently at [ogn-skylines-gateway](https://github.com/kerel-fs/ogn-skylines-gateway), but I would like to move it to skylines).

**Comment by Turbo87** [comment]
@kerel-fs it's probably best if you push your current state to your fork and open a WIP pull request for it. That way we can review what's there and hopefully give helpful comments

**Comment by Turbo87** [comment]
to cut down on the number of open issues on this project we are introducing a feature request queue: https://github.com/skylines-project/skylines/issues?q=label%3Afeature-request+is%3Aclosed+sort%3Areactions-%2B1+. we will close feature requests immediately and label them with "feature-request" so that they will show up in the queue, which is sorted by 👍 reactions. since this issue is also a feature request we have labeled it appropriately and will close it now.
