### ISSUE TITLE
Export user data as JSON blob

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#784]
GDPR demands that a user can export all their related data in a machine-readable format. We will need to add a button that allows that.

### Todo

- [ ] figure out what counts as "user data"
- [ ] implement code that exports all "user data" in a zip file and sends a link to it in an email to the user
  - [ ] change the filename to a hash of the content to make the public link sent to the user hard to guess
  - [ ] configure nginx to serve the folder including the zip files on a public endpoint
- [ ] add API endpoint that triggers a background job running the new export code for the current user
  - [ ] require user to provide their password when triggering an export (to prevent accidental clicks and load on the server)
- [ ] expose new API endpoint as a button in the account settings
  - [ ] force user to enter his password (without autofill) before triggering the API call

**Comment by lordfolken** [comment]
Closing as stale/wontfix in 2026 revitalization triage; reopen with fresh repro if still relevant.
