### ISSUE TITLE
Add Privacy Policy

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#785]
GDPR requires us to add a Privacy Policy document to the site explaining how we handle all of the data in plain English. I assume that English would be enough and that we don't have to translate it in all the different languages.

more resources available at:

- https://ico.org.uk/for-organisations/guide-to-data-protection/privacy-notices-transparency-and-control/what-should-you-include-in-your-privacy-notice/
- https://ico.org.uk/for-organisations/guide-to-data-protection/privacy-notices-transparency-and-control/privacy-notices-under-the-eu-general-data-protection-regulation/

### Todo

- [x] gather information on what to include in the "Privacy Policy"
- [x] write "Privacy Policy" in prose form (e.g. as a `PRIVACY.md` file in this repository; see #868)
- [x] include link to "Privacy Policy" in the frontend (see #868)
- [ ] figure out if existing accounts need to add explicit consent to the new "Privacy Policy" and if so:
  - [ ] add new field to the `users` table that tracks that consent
  - [ ] add API to change consent status (can likely be added to something like `POST /account`)
  - [ ] check consent status on next login (of token renewal) and prevent further actions before consent is given
- [ ] send emails to all current users about the new "Privacy Policy"

**Comment by Turbo87** [comment]
### Examples

- https://wiki.openstreetmap.org/wiki/Privacy_Policy
- https://wikimediafoundation.org/wiki/Privacy_policy
