### ISSUE TITLE
Add "Delete Account" functionality 

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#786]
GDPR requires us to allow users to delete their accounts.

### Todo

- [ ] add API endpoint that can delete the current account (e.g. `DELETE /account`)
  - [ ] protect API endpoint with the current account password to prevent accidental account deletion
  - [ ] ensure that related data is updated as appropriate or deleted too (e.g. flight comments could show "Deleted User", flights from the deleted user should be deleted too)
- [ ] expose the new API endpoint as a button in the user settings
  - [ ] force user to enter their current password before calling the API

**Comment by Turbo87** [comment]
### `User` references

- club.owner_id
- event.actor_id
- event.user_id
- flight.pilot_id
- flight.co_pilot_id
- flight_comment.user_id
- follower.source_id
- follower.destination_id
- igc_file.owner_id
- notification.recipient_id
- refresh_token.user_id
- tracking.pilot_id

**Comment by Turbo87** [comment]
Resolved by #840
