### ISSUE TITLE
Remove account information from Sentry bug reports

### ISSUE THREAD

**Issue by Turbo87** [skylines-project/skylines#787]
We use https://sentry.io/ as a bug reporting service that notifies us when the Frontend or the API runs into unexpected issues. We currently add account information (id + name + email address) to the bug reports so that we can associate them to a user account and be able to reproduce the issue better. While sharing a user id in my understanding of the GDPR rules is still okay, we should stop adding the name and email address to the bug reports.

### Todo

- [x] figure out if only frontend or the API too is sharing that information
- [x] remove extra information from frontend bug reporting code (`raven` service)
- [ ] (if applicable) remove extra information from API bug reporting code
